### ISSUE TITLE
Unable to delete a newline

### ISSUE THREAD

**Issue by iautom8things** [BeaconCMS/live_monaco_editor#10]
Hi, thank you for this!  I'm having issues using this in a form.  After hitting `enter` to do a new line I'm unable to backspace through the newline to delete it.  Before hitting `enter` backspace works fine.  Here is a quick recording of this in action:

![Screen Recording 2023-06-15 at 08 20 02 AM](https://github.com/BeaconCMS/live_monaco_editor/assets/522040/4064cedb-0876-4cfe-9edd-0df508cb656b)

I've set up an example repo that is just a base phoenix app with minimal changes to show this problem: [test_monaco](https://github.com/iautom8things/test_monaco)

This is happening on a Mac w/ Safari, Chrome and Arc browsers.

Thank you, again!

**Comment by leandrocp** [comment]
Hey @iautom8things thanks for the detailed report. Support for forms is a bit tricky, I suggest to fetch the editor content with an event listener instead:

```elixir
# firstly we need to ignore events trigger by the editor
  def handle_event(
        "validate",
        %{
          "_target" => ["live_monaco_editor", @new_query_path]
        },
        socket
      ) do
    {:noreply, socket}
  end
```

And then fetch the content as explained here https://github.com/BeaconCMS/live_monaco_editor#fetching-the-editor-value

**Comment by leandrocp** [comment]
Hey @iautom8things I'm closing this one but feel free to comment here or submit a new issue. Thanks.
