### ISSUE TITLE
Possible to set the contents (via Liveview)?

### ISSUE THREAD

**Issue by rliebling** [BeaconCMS/live_monaco_editor#11]
Nice job on this - i greatly appreciate the effort.

I'm wondering if there's a way to have Liveview update the contents of the LME (editor)?  I'm sure there must be, with sufficient Javascript.  But, without having to dig into the internals of the MS Monaco editor, is there a reasonable way?  Any pointers would be appreciated.   I was hoping that the editor provides an API for this that can be easily accessilble, or syncs the contents with a JS variable that I can write to (and trigger the editor to refresh)

I tried the obvious - having the `value` of the `<LiveMonacoEditor.code_editor>` be a liveview variable (eg `value={@my_state_variable}` but that did not work (other than the initial value).

For context, I'd like to use this as a SQL editor but also have a dropdown of previous queries for the user to choose from, and populate the editor when the user chooses a value from the dropdown.

**Comment by rliebling** [comment]
My apologies - i see you have provided a means via:
```
socket = LiveMonacoEditor.set_value(socket, new_value, to: "PATH_ASSIGNED_TO_EDITOR_INSANCE")
```
and documented it in the README.md.  Somehow I saw the section as only about *Change Language" and missed the part about also changing the value -- so much for my reading comprehension score :)

anyway, thanks again for providing this!

**Comment by leandrocp** [comment]
Hey @rliebling I'm glad you find it :)
For future reference, you can't assign the value since we need to call the monaco api on the js land.
