### ISSUE TITLE
Form posts incomplete data after 10lines

### ISSUE THREAD

**Issue by rliebling** [BeaconCMS/live_monaco_editor#14]
I can reproduce this by running `iex -S mix dev` in this project.  If you edit the `file_c` box adding up to 10 lines all works fine.  but, as soon as you add an 11th line incomplete data is sent to the `handle_event` call (and output in the `iex -S mix dev` console.  basically you get the 11th line onwards.  It seems like the editor is using 10line windows of text to serialize as part of the form data.

I am willing to investigate this more, but am rather confused right now on how this is supposed to work.  Does this project (the elixir project) do anything to make the form stuff work?  Or, does the monaco editor keep some textarea or other form element in sync with the text of the monaco editor so that `live_monaco_editor` does not need to do anything?  If so, then this seems to be an issue with the underlying monaco editor - which I believe is the case, although it may be intended behavior.  

Again, starting this as a discussion.  And, it may well be a case of user-error, although i hoped the `iex -S mix dev` eliminated that chance.  thanks in advance for any help/guidance you can provide!

**Comment by leandrocp** [comment]
Hey @rliebling thanks for looking into it. The monaco editor and phx-change aren't playing nice together so I recommend https://github.com/BeaconCMS/live_monaco_editor#fetching-the-editor-value instead to fetch the editor content value.

I'd like to make it work but I'm afraid that may require deeper changes to Phoenix or even the Monaco editor, making such feature not viable. But before ruling it out it's worth investigating a bit more.

**Comment by leandrocp** [comment]
It's actually a bit more complicated :D
Monaco will create a textarea but the actual content is kept inside a tree of div>span elements. AFAIK it works this way so Monaco can render visual elements, syntax highlight, and so on, ie: have total control of the editor. So I _suspect_ the textarea works like a buffer and phx-change won't capture all the content. My initial thought was to somehow intercept the change event, capture the entire editor content, and update the value. But I'm not sure if that's doable.

**Comment by leandrocp** [comment]
To help with that problem I've released a new version with a new `:change` option that mimics phx-change but doesn't have those limitations. See https://github.com/BeaconCMS/live_monaco_editor/pull/19 and https://github.com/BeaconCMS/live_monaco_editor#inside-forms

I'm closing this one for now but feel free to reopen it or add more comments. Thanks!

**Comment by apoorv-2204** [comment]
what about phx debounce for throttling events?
